server:
  port: 8090  # 端口号
  servlet:
    context-path: '/renting'  #项目访问路径

spring:
  datasource: # 数据源
    url: jdbc:mysql://localhost:3306/renting?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    #serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123@qwe
  jackson:
    date-format: 'yyyy-MM-dd' # 格式化json
